import { NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

const MOCK_MENU = {
  restaurant: {
    id: 'demo-restaurant-id',
    name: 'Spice Garden',
    slug: 'spice-garden-lahore',
    isOpen: true,
    deliveryFee: 150,
    minOrder: 500,
  },
  categories: [
    {
      id: 'cat-starters',
      name: 'Starters',
      description: 'Light bites and appetisers to begin your journey',
      items: [
        {
          id: 'item-chicken-tikka-boti',
          name: 'Chicken Tikka Boti',
          description: 'Tender chicken chunks marinated in yoghurt and aromatic spices, skewered and grilled to perfection in our clay tandoor. Served with mint chutney and sliced onions.',
          price: 650,
          imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['halal', 'spicy'],
          preparationTime: 20,
          modifiers: [],
        },
        {
          id: 'item-seekh-kabab',
          name: 'Seekh Kabab',
          description: 'Hand-minced beef blended with green chillis, fresh herbs and select spices, shaped on skewers and char-grilled over coal. 4 pieces served with raita.',
          price: 750,
          imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['halal', 'spicy'],
          preparationTime: 18,
          modifiers: [],
        },
        {
          id: 'item-samosa-chaat',
          name: 'Samosa Chaat',
          description: 'Crispy potato-filled samosas crushed and topped with spiced chickpeas, tangy tamarind chutney, cooling yoghurt, sev and fresh coriander.',
          price: 400,
          imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['vegetarian'],
          preparationTime: 10,
          modifiers: [],
        },
        {
          id: 'item-dahi-bhalle',
          name: 'Dahi Bhalle',
          description: 'Soft lentil dumplings soaked in cool whipped yoghurt, drizzled with sweet and tangy chutneys and sprinkled with roasted cumin and chaat masala.',
          price: 350,
          imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['vegetarian'],
          preparationTime: 8,
          modifiers: [],
        },
      ],
    },
    {
      id: 'cat-mains',
      name: 'Mains',
      description: 'Hearty main courses bursting with flavour',
      items: [
        {
          id: 'item-chicken-karahi',
          name: 'Chicken Karahi',
          description: 'Our signature dish — fresh-cut chicken cooked in a cast-iron karahi with tomatoes, green chillis, ginger, garlic and hand-ground spices. Finished with butter and cream.',
          price: 1200,
          imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['halal', 'spicy'],
          preparationTime: 25,
          modifiers: [
            {
              id: 'mod-karahi-size',
              name: 'Serving Size',
              options: [{ label: 'Half (500g)', price: 0 }, { label: 'Full (1kg)', price: 400 }],
              required: true,
              maxSelections: 1,
            },
            {
              id: 'mod-karahi-extras',
              name: 'Extras',
              options: [{ label: 'Extra Naan', price: 80 }, { label: 'Extra Raita', price: 80 }, { label: 'Extra Butter', price: 50 }],
              required: false,
              maxSelections: 3,
            },
          ],
        },
        {
          id: 'item-beef-biryani',
          name: 'Beef Biryani',
          description: 'Slow-cooked dum biryani with tender beef, aged basmati rice, saffron, caramelised onions and whole spices. Each grain of rice absorbs the rich meat juices.',
          price: 900,
          imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['halal', 'spicy'],
          preparationTime: 35,
          modifiers: [
            {
              id: 'mod-biryani-portion',
              name: 'Portion',
              options: [{ label: 'Half Portion', price: 0 }, { label: 'Full Portion (for 2)', price: 350 }],
              required: true,
              maxSelections: 1,
            },
          ],
        },
        {
          id: 'item-lamb-nihari',
          name: 'Lamb Nihari',
          description: 'A Lahori classic — slow-braised lamb shank simmered overnight in a rich, deeply spiced gravy. Garnished with ginger, fried onions, fresh lime and green chillis.',
          price: 1400,
          imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['halal'],
          preparationTime: 30,
          modifiers: [],
        },
        {
          id: 'item-palak-paneer',
          name: 'Palak Paneer',
          description: 'Fresh cottage cheese cubes in a velvety spinach gravy with garlic, ginger and gentle spices. A wholesome vegetarian main served with naan.',
          price: 750,
          imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['vegetarian', 'gluten-free'],
          preparationTime: 20,
          modifiers: [],
        },
        {
          id: 'item-chana-masala',
          name: 'Chana Masala',
          description: 'Hearty chickpeas cooked in an aromatic tomato and onion masala, slow-simmered with whole spices and finished with fresh coriander and a squeeze of lime.',
          price: 600,
          imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['vegetarian', 'vegan', 'halal', 'gluten-free'],
          preparationTime: 15,
          modifiers: [],
        },
      ],
    },
    {
      id: 'cat-grills',
      name: 'Grills',
      description: 'Sizzling BBQ and tandoor specialities',
      items: [
        {
          id: 'item-mixed-grill-platter',
          name: 'Mixed Grill Platter',
          description: 'The ultimate BBQ experience — seekh kababs, chicken tikka, lamb chops and shami kababs. Served with bread, raita and salad.',
          price: 2800,
          imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['halal'],
          preparationTime: 30,
          modifiers: [],
        },
        {
          id: 'item-lamb-chops',
          name: 'Lamb Chops',
          description: 'Premium lamb rib chops marinated overnight in yoghurt, raw papaya and spices, grilled over coal for a smoky char. 4 pieces per portion.',
          price: 2200,
          imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['halal'],
          preparationTime: 25,
          modifiers: [],
        },
        {
          id: 'item-tandoori-whole-chicken',
          name: 'Tandoori Whole Chicken',
          description: 'A full spring chicken marinated in our house tandoori spice blend and yoghurt, roasted in the clay oven until charred on the outside and juicy within.',
          price: 1800,
          imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['halal'],
          preparationTime: 40,
          modifiers: [],
        },
        {
          id: 'item-reshmi-kabab',
          name: 'Reshmi Kabab',
          description: 'Silky smooth minced chicken kababs made with cashew paste, cream and mild spices, grilled on skewers for a melt-in-the-mouth texture. 3 pieces served.',
          price: 950,
          imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['halal'],
          preparationTime: 22,
          modifiers: [],
        },
      ],
    },
    {
      id: 'cat-beverages',
      name: 'Beverages',
      description: 'Refreshing drinks and traditional favourites',
      items: [
        {
          id: 'item-mango-lassi',
          name: 'Mango Lassi',
          description: 'Fresh Chaunsa mango blended with thick yoghurt, chilled milk and a pinch of cardamom. Sweet, creamy and quintessentially Pakistani.',
          price: 280,
          imageUrl: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['vegetarian'],
          preparationTime: 5,
          modifiers: [],
        },
        {
          id: 'item-rooh-afza-sharbat',
          name: 'Rooh Afza Sharbat',
          description: 'The iconic Pakistani rose sherbet mixed with cold milk and rose petals. Refreshingly sweet and floral — a summer classic.',
          price: 200,
          imageUrl: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['vegetarian'],
          preparationTime: 3,
          modifiers: [],
        },
        {
          id: 'item-kashmiri-chai',
          name: 'Kashmiri Chai',
          description: 'Traditional pink Kashmiri tea brewed with special tea leaves and baking soda, finished with warm milk, cream, pistachios and cardamom.',
          price: 320,
          imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['vegetarian'],
          preparationTime: 8,
          modifiers: [],
        },
        {
          id: 'item-fresh-lime-soda',
          name: 'Fresh Lime Soda',
          description: 'Freshly squeezed lime juice with chilled sparkling water, a pinch of black salt and mint leaves. The perfect palate cleanser.',
          price: 180,
          imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['vegetarian', 'vegan'],
          preparationTime: 3,
          modifiers: [],
        },
      ],
    },
    {
      id: 'cat-desserts',
      name: 'Desserts',
      description: 'Sweet endings to complete your meal',
      items: [
        {
          id: 'item-gulab-jamun',
          name: 'Gulab Jamun',
          description: 'Soft khoya dumplings deep-fried to a golden brown and soaked in fragrant rose-water sugar syrup. Served warm with a sprinkle of pistachios. 4 pieces.',
          price: 300,
          imageUrl: 'https://images.unsplash.com/photo-1567206563114-c179900d4f75?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['vegetarian'],
          preparationTime: 10,
          modifiers: [],
        },
        {
          id: 'item-kheer',
          name: 'Kheer',
          description: 'Slow-cooked rice pudding simmered in full-fat milk with sugar, cardamom, saffron and rose water. Garnished with blanched almonds and pistachios.',
          price: 280,
          imageUrl: 'https://images.unsplash.com/photo-1505253304499-671c55fb57fe?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['vegetarian', 'gluten-free'],
          preparationTime: 12,
          modifiers: [],
        },
        {
          id: 'item-kulfi-faluda',
          name: 'Kulfi Faluda',
          description: 'Traditional Pakistani frozen milk dessert served on a bed of rose-flavoured faluda vermicelli, basil seeds and a drizzle of sweet syrup.',
          price: 380,
          imageUrl: 'https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=400&q=70',
          isAvailable: true,
          dietaryTags: ['vegetarian'],
          preparationTime: 5,
          modifiers: [],
        },
      ],
    },
  ],
}

export async function GET(request: Request) {
  // Try real DB first, fall back to mock data
  try {
    const { prisma } = await import('@/lib/db/prisma')
    const { searchParams } = new URL(request.url)
    const restaurantId = searchParams.get('restaurantId')
    const whereRestaurant = restaurantId ? { id: restaurantId } : {}
    const restaurant = await prisma.restaurant.findFirst({
      where: whereRestaurant,
      select: { id: true, name: true, slug: true, isOpen: true, deliveryFee: true, minOrder: true },
    })
    if (!restaurant) return NextResponse.json(MOCK_MENU)
    const categories = await prisma.menuCategory.findMany({
      where: { restaurantId: restaurant.id, isActive: true },
      orderBy: { sortOrder: 'asc' },
      include: { items: { orderBy: { name: 'asc' }, include: { modifiers: true } } },
    })
    return NextResponse.json({ restaurant, categories })
  } catch {
    return NextResponse.json(MOCK_MENU)
  }
}
